//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealtProWpfApp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class House
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public House()
        {
            this.AdditionalImageOfHouses = new HashSet<AdditionalImageOfHouse>();
        }
    
        public int Id { get; set; }
        public string District { get; set; }
        public string Street { get; set; }
        public string House1 { get; set; }
        public string NumberOfFloors { get; set; }
        public string TotalArea { get; set; }
        public string LivingSpace { get; set; }
        public string NumberOfRooms { get; set; }
        public int BathroomId { get; set; }
        public int MarketId { get; set; }
        public double YearOfConstruction { get; set; }
        public int MaterialId { get; set; }
        public int AdOwnerId { get; set; }
        public byte[] MainImage { get; set; }
        public decimal Price { get; set; }
        public string KitchenArea { get; set; }
        public string LandArea { get; set; }
        public int SewerageId { get; set; }
        public int WaterSupplyId { get; set; }
        public int HeatingId { get; set; }
        public int GasSupplyId { get; set; }
        public int TypeId { get; set; }
        public int RealtorId { get; set; }
        public Nullable<int> DeveloperId { get; set; }
        public int ClientId { get; set; }
        public string Notes { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDateOfWork { get; set; }
        public int ObjectStatusId { get; set; }
        public string AgentCommission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdditionalImageOfHouse> AdditionalImageOfHouses { get; set; }
        public virtual AdOwner AdOwner { get; set; }
        public virtual Bathroom Bathroom { get; set; }
        public virtual Client Client { get; set; }
        public virtual Developer Developer { get; set; }
        public virtual GasSupply GasSupply { get; set; }
        public virtual Heating Heating { get; set; }
        public virtual Market Market { get; set; }
        public virtual Material Material { get; set; }
        public virtual ObjectStatu ObjectStatu { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual Sewerage Sewerage { get; set; }
        public virtual Type Type { get; set; }
        public virtual WaterSupply WaterSupply { get; set; }
    }
}
